// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuDHOc_bcpDtE6HS6WIP4PtqyiKamN_SU',
    appId: '1:81083093155:web:97b93d224accde6ce6af16',
    messagingSenderId: '81083093155',
    projectId: 'auth-modul-4ce18',
    authDomain: 'auth-modul-4ce18.firebaseapp.com',
    storageBucket: 'auth-modul-4ce18.firebasestorage.app',
    measurementId: 'G-0EXT6NM849',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjHHz3g_gM8clQBHhOSG0LXpsmKez4Po0',
    appId: '1:81083093155:android:e033661f293b52d8e6af16',
    messagingSenderId: '81083093155',
    projectId: 'auth-modul-4ce18',
    storageBucket: 'auth-modul-4ce18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1A0dRI61KMmLqpxINYMBiE6o5wInSGiU',
    appId: '1:81083093155:ios:3d39a95e70f1b849e6af16',
    messagingSenderId: '81083093155',
    projectId: 'auth-modul-4ce18',
    storageBucket: 'auth-modul-4ce18.firebasestorage.app',
    iosBundleId: 'com.example.appAuthFirebasePpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1A0dRI61KMmLqpxINYMBiE6o5wInSGiU',
    appId: '1:81083093155:ios:3d39a95e70f1b849e6af16',
    messagingSenderId: '81083093155',
    projectId: 'auth-modul-4ce18',
    storageBucket: 'auth-modul-4ce18.firebasestorage.app',
    iosBundleId: 'com.example.appAuthFirebasePpb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuDHOc_bcpDtE6HS6WIP4PtqyiKamN_SU',
    appId: '1:81083093155:web:60e66295c17b9db0e6af16',
    messagingSenderId: '81083093155',
    projectId: 'auth-modul-4ce18',
    authDomain: 'auth-modul-4ce18.firebaseapp.com',
    storageBucket: 'auth-modul-4ce18.firebasestorage.app',
    measurementId: 'G-KL0NJFJ00K',
  );
}
